language: ruby
rvm:
  - 2.2.2

addons:
  postgresql: "9.4"

before_install: gem install bundler -v 1.10.6;
before_script:
  - cp config/database.yml.travis config/database.yml

notifications:
  email: false
