cache: bundler

language: ruby

rvm:
  - 2.2.2

addons:
  postgresql: '9.4'

before_script:
  - psql -c 'create database openipsum-api-v2_test;' -U postgres

notifications:
  email: false

script:
  - bundle exec rake rubocop
  - bundle exec rake spec
