cache: bundler
language: ruby
rvm:
- 2.2.3
addons:
  ssh_known_hosts: api.openipsum.com
before_script:
- psql -c "create database openipsumapitest;" -U postgres
notifications:
  email: false
script:
- bundle exec rake rubocop
- bundle exec rake spec
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 deployment/deploy_key.pem
- ssh-add deployment/deploy_key.pem
- git remote add deploy "ssh://ubuntu@api.openipsum.com/home/ubuntu/git-deploys/api.git"
- git push -u deploy master
before_install:
- openssl aes-256-cbc -K $encrypted_9ad051952287_key -iv $encrypted_9ad051952287_iv
  -in deployment/deploy_key.pem.enc -out deployment/deploy_key.pem -d
