cache: bundler
language: ruby
rvm:
- 2.2.2
addons:
  postgresql: '9.4'
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
notifications:
  email: false
script:
- bundle exec rake rubocop
- bundle exec rake spec

deploy:
  provider: heroku
  api_key:
    secure: pVARDxyvBO85+XFWSZkXxsdr+sfg2+MzZuS/VafRO1X0mWpPQUa9tt19fIowwom70ByRDJQz9OUYXF9Lp3+wor/NH61HdygacGoXvktkjGDgVHaXXZNteiuCrMHVzdYfBVFt9NprEdyAgexxqb9/DcnUOfKyr9n88OCIPo5fu3Lysw2FLzHyj8im8EdX+GFz5LLlazls497mYZhObALgLNCfvUEp58QWt42X0dFlUakZYS7F4lI8JBgmyaObfmEBqHHY/qWdPpE4gjrfZwOAJTgM2VeLpbYMvvDmJfWa8AdiukSIm7AwAkO4OjI14o+3FCtqJJ/VR+O4u4bldyiop4CIL13RxtKx8oMua9w647K/7/aCeGTOnMMaWybsy/kvYexnQKTyY21WNOez4cXpJSgfHoksIFGC62iR+cZPUjc7plMlBXIn6m6nAZMIqP2Td+2A3Zp5hIwQO2nP07Mt4X8c2z9zUxa9zJeRCcAmQukJeEvLUMW6oL6qmdEs5PaiWVSsn2qs5rTduy18Fpb7i0vWzna6WyUE/PTUwVYyNPcnsv9bP0jy6qqA8xSnZjw+I6EQiVG9RgmNTiL7+R9L1AG3dT/1S0fGqKevitK3qciqkPX0FOeUTvkuoSUHlL5GFi00UtflRMtPpMD//xzj+0zG/8F0OMKOe2BLk+NylJ0=
  app: afternoon-stream-9346
  on:
    repo: jaxgeller/open-ipsum-api
