cache: bundler
language: ruby
rvm:
- 2.2.3
addons:
  ssh_known_hosts: api.openipsum.com
before_script:
- psql -c "create database openipsumapitest;" -U postgres
notifications:
  email: false
script:
- bundle exec rake rubocop
- bundle exec rake spec
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 deployment/deploy_key.pem
- ssh-add deployment/deploy_key.pem
- git remote add deploy $DEPLOY_URL
- git push deploy
before_install:
- openssl aes-256-cbc -K $encrypted_9ad051952287_key -iv $encrypted_9ad051952287_iv
  -in deployment/deploy_key.pem.enc -out deployment/deploy_key.pem -d
env:
  global:
    secure: omWM+hJV6u8CGubw87hqsuZBxiVgz3dNYM6Ibs5zVhQON/Je/yIPcNKC3ZgdFvH6W33ABSi5T7if2tXj0M1E4R9dr+Udf8dXBEwrd632Eh9DbB4LcOTeX969FqZDZUkG46dVqqM7EaQAtzJhM9SGwEA+5awl8imevlGrh7FJwG9yPKrUOCiIh+AiASrjtQ71j/uTXtWltGyZgf2s1sNRbomAH36tSxhiC4xhYb5EMdscUDhmEVx+CC1CL0xMkVn4ir4V1axPqtbCmyRgVQ805Qy9GHXXENAQkaSR2OBQnEKeOSOvO5ao6+gBNYWZfw7/cgV016dYtR6n+ZCnKyIrs9SRbDgmaCJ5cG/kXyqRzEI5rz/Dx/ucdVR4ytb5RWxXJZclGFpz8COkkkcTue6bTaI4r99YKElGKTalZSyzdqiHhWMWSNmJ+Kx1JUaQFZBoVHGw8+dcxobbwUGF4RgBUDo7/hRSgRc+fYn5Yykk8w1+aTe+iHUv1b7kXQFNmb6qncRfTbgB8ldlTYnXDYmq4ccXtxPMW+NSBWkQmX/N/+SBmuqe0m5hXfWgGVpuEN3dq09NHEm+RRACqO1GAjlsvo5T8939p0hM+Gi53SgjYPN3leG2J3tqpHxvb/OFG96bBGQl9a3IkdTXml+7sOP44Hsm9aZV0CvFZLrGpx6NhGg=
