default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: openipsum-api-v2_development

test:
  <<: *default
  database: "openipsumapitest"
  username: postgres

production:
  <<: *default
  database: <%= ENV['OPENIPSUM_API_DATABASE'] %>
  username: <%= ENV['OPENIPSUM_API_DATABASE_USERNAME'] %>
  password: <%= ENV['OPENIPSUM_API_DATABASE_PASSWORD'] %>
